version: "3.9"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
      - ./redis/custom.conf:/usr/local/etc/redis/redis.conf
    env_file: ./src/.env.production
    networks:
      - app-network
  hippo-api:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - hippo-api-vendor:/var/www/html/vendor
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    env_file: ./src/.env.production
    deploy:
      replicas: 3
    environment:
      - CONTAINER_ROLE=app
  queue:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:cached
      - hippo-api-vendor:/var/www/html/vendor:cached
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    env_file: ./src/.env.production
    environment:
      - CONTAINER_ROLE=queue
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/local-servers:/etc/nginx/servers
    depends_on:
      - hippo-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  hippo-api-vendor:
    driver: local
