version: "3.9"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
      - ./redis/custom.conf:/usr/local/etc/redis/redis.conf
    env_file: ./src/.env.production
    networks:
      - app-network
  hippo-api:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:cached
      - hippo-api-vendor:/var/www/html/vendor:cached
    networks:
      - app-network
    env_file: ./src/.env.production
    deploy:
      replicas: 3
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/servers:/etc/nginx/servers
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    depends_on:
      - hippo-api
    networks:
      - app-network
  certbot:
    image: certbot/certbot:latest
    command: sh -c "certbot certonly --standalone -d api-v2.hippo.cards --text --agree-tos --email batsoyombo.kh@gmail.com --server https://acme-v02.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  hippo-api-vendor:
    driver: local
