<?php

namespace App\Enums;

enum EPermissionScope: string
{
    case READ_PACKAGE = 'READ_PACKAGE';
    case CREATE_PACKAGE = 'CREATE_PACKAGE';
    case UPDATE_PACKAGE = 'UPDATE_PACKAGE';
    case DELETE_PACKAGE = 'DELETE_PACKAGE';
    case READ_WORD = 'READ_WORD';
    case CREATE_WORD = 'CREATE_WORD';
    case UPDATE_WORD = 'UPDATE_WORD';
    case DELETE_WORD = 'DELETE_WORD';
    case READ_INVOICE = 'READ_INVOICE';
    case READ_USERS = 'READ_USERS';
    case UPDATE_USER = 'UPDATE_USER';
    case UPDATE_USER_SUBSCRIPTION = 'UPDATE_USER_SUBSCRIPTION';
    case CREATE_COURSE = 'CREATE_COURSE';
    case UPDATE_COURSE = 'UPDATE_COURSE';
    case DELETE_COURSE = 'DELETE_COURSE';
    case ADD_BLOCK_COURSE = 'ADD_BLOCK_COURSE';
    case MOVE_BLOCK_COURSE = 'MOVE_BLOCK_COURSE';
    case REMOVE_BLOCK_COURSE = 'REMOVE_BLOCK_COURSE';
    case UPDATE_BLOCK_COURSE = 'UPDATE_BLOCK_COURSE';
    case MANAGE_IMAGE_BLOCK_COURSE = 'MANAGE_IMAGE_BLOCK_COURSE';
    case MANAGE_SENTENCE_BLOCK_COURSE = 'MANAGE_SENTENCE_BLOCK_COURSE';
    case MANAGE_VIDEO_BLOCK_COURSE = 'MANAGE_VIDEO_BLOCK_COURSE';
}
