<?php

namespace App\Enums;

use App\Traits\EnumWithValues;

enum EUserPreferenceValue: string
{
    case OTHERS = 'OTHERS';

    case OBJECTIVE_TRAVEL_STUDY = 'OBJECTIVE_TRAVEL_STUDY';
    case OBJECTIVE_COMMUNICATION = 'OBJECTIVE_COMMUNICATION';
    case OBJECTIVE_SELF_IMPROVEMENT = 'OBJECTIVE_SELF_IMPROVEMENT';
    case OBJECTIVE_CARRER_ADVANCEMENT = 'OBJECTIVE_CARRER_ADVANCEMENT';
    case OBJECTIVE_KIDS_COMMUNICATION = 'OBJECTIVE_KIDS_COMMUNICATION';

    case SKILL_SPEAKING = 'SKILL_SPEAKING';
    case SKILL_LISTENING = 'SKILL_LISTENING';
    case SKILL_PRONUNCIATION = 'SKILL_PRONUNCIATION';
    case SKILL_WRITING = 'SKILL_WRITING';
    case SKILL_GRAMMAR = 'SKILL_GRAMMAR';
    case SKILL_VOCABULARY = 'SKILL_VOCABULARY';

    case STUDY_TIME_MORNING = 'STUDY_TIME_MORNING';
    case STUDY_TIME_AFTERNOON = 'STUDY_TIME_AFTERNOON';
    case STUDY_TIME_NIGHT = 'STUDY_TIME_NIGHT';

    case STUDY_REPETITION_DAILY = 'STUDY_REPETITION_DAILY';
    case STUDY_REPETITION_WEEKLY = 'STUDY_REPETITION_WEEKLY';
    case STUDY_REPETITION_MONTHLY = 'STUDY_REPETITION_MONTHLY';
    case STUDY_REPETITION_SELDOM = 'STUDY_REPETITION_SELDOM';
}
