# Version 1
name: Demo workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HIPPO_SECONDARY_SERVER_HOST }}
          username: ${{ secrets.HIPPO_SECONDARY_SERVER_USERNAME }}
          key: ${{ secrets.HIPPO_SECONDARY_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd hippo/hippocards-backend/src
            sudo -u www-data git pull origin main
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo supervisorctl restart laravel-worker:*
